# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  build:
    desc: Builds the app
    cmds:
      - go build -o bin/ocm_meta -v main.go
  run:
    desc: Start the app
    cmds:
      - run bin/ocm_meta
